### ISSUE TITLE
It won't show anything

### ISSUE THREAD

**Issue by luizamfsantos** [Platane/snk#89]
I don't know what is wrong. Could someone help me?
https://github.com/luizamfsantos/luizamfsantos/blob/main/.github/workflows/main.yml

**Comment by Platane** [comment]
It might be related to this one

https://github.com/Platane/Platane/issues/9#issuecomment-1674230829

**Comment by UTshion** [comment]
Hello.

If you run the Github Action and it returns an error, please check the error statement by clicking "generate animation" in the "Actions" page of your repository.

If you find the senteces like the below, errors you get are caused by Permission Settings of your repository. 
- remote: Permission to <username>/<repository_name>.git denied to github-actions[bot].
- fatal: unable to access 'https://github.com/<username>/<repository_name>.git/': The requested URL returned error: 403
- Error: The process '/usr/bin/git' failed with exit code 128.

In that case, you can solve the problem by following method.
1. In your repository, select **Settings > Actions > General** for opening Github Actions settings.
2. In "Workflow permissions" heading, check the item "Read and write permissions" and save that change.

![1](https://github.com/Platane/snk/assets/16451897/32028541-6f64-4b6e-aa21-f9fe70003b2e)

3. Run "generate animation" action again, and you may get a successful result!

![2](https://github.com/Platane/snk/assets/16451897/ea4dcec5-3f2c-4a3c-af83-eb6192f24933)

I hope this helps you!
